### ISSUE TITLE
请问您是中国人吗？我最近在解决pm2下log4js的日志打印问题。

### ISSUE THREAD

**Issue by Gitforxuyang** [liujingbreak/log4js-pm2-intercom#1]
我在找PM-intercom源码的时候找到了您的分享。请问您的这份源码是自己实现的还是从官方的原始版本改的？

**Comment by liujingbreak** [comment]
@Gitforxuyang  这份源码是看了当初官方源码上改的，但是PM2"官方"其实没有开源，并且似乎已经下架了，新的官网不再能找到，所以我不认为他们愿意保证他们当初的代码支持现在的PM2版本，我的代码在目前仅在自己公司的产品上使用，但愿里并不复杂，你能看到源码只有几行
